#!/usr/bin/env python3
"""Emit compact codepoint-range tables for the Unicode categories the
tokenizer's splitter needs (\\p{L}, \\p{N}, \\p{M}).

Generated rather than hand-written: the ranges come from Python's own Unicode
database, so they cannot drift from what the reference tokenizer sees."""
import sys, unicodedata

def cat_ranges(pred, maxcp=0x110000):
    out, start = [], None
    for cp in range(maxcp):
        if pred(cp):
            if start is None: start = cp
        elif start is not None:
            out.append((start, cp - 1)); start = None
    if start is not None: out.append((start, maxcp - 1))
    return out

def cat(cp):
    try: return unicodedata.category(chr(cp))
    except ValueError: return "Cn"

L = cat_ranges(lambda c: cat(c).startswith("L"))
N = cat_ranges(lambda c: cat(c).startswith("N"))
M = cat_ranges(lambda c: cat(c).startswith("M"))

def emit(name, rs, f):
    print(f"// {len(rs)} ranges", file=f)
    print(f"static const uint32_t k{name}[][2] = {{", file=f)
    for i in range(0, len(rs), 6):
        print("    " + " ".join(f"{{0x{a:X},0x{b:X}}}," for a, b in rs[i:i+6]), file=f)
    print("};", file=f)
    print(f"static const int kN{name} = {len(rs)};\n", file=f)

with open("src/unicode_tables.h", "w") as f:
    print("#pragma once", file=f)
    print("// GENERATED by tools/gen_unicode.py -- do not edit.", file=f)
    print("// Codepoint ranges for the Unicode categories the tokenizer's", file=f)
    print("// pre-tokenizer regex needs. Derived from Python's unicodedata so", file=f)
    print("// they cannot drift from what the reference tokenizer sees.", file=f)
    print("#include <stdint.h>\n", file=f)
    emit("Letter", L, f)
    emit("Number", N, f)
    emit("Mark", M, f)
    print("""static inline bool in_ranges(const uint32_t (*r)[2], int n, uint32_t c) {
  int lo = 0, hi = n - 1;
  while (lo <= hi) {
    const int mid = (lo + hi) >> 1;
    if (c < r[mid][0]) hi = mid - 1;
    else if (c > r[mid][1]) lo = mid + 1;
    else return true;
  }
  return false;
}
static inline bool uc_is_letter(uint32_t c) { return in_ranges(kLetter, kNLetter, c); }
static inline bool uc_is_number(uint32_t c) { return in_ranges(kNumber, kNNumber, c); }
static inline bool uc_is_mark(uint32_t c)   { return in_ranges(kMark,   kNMark,   c); }""", file=f)
print(f"L={len(L)} N={len(N)} M={len(M)} ranges", file=sys.stderr)

# ---- NFC: canonical combining classes + composition pairs -------------------
# The reference tokenizer NFC-normalises before splitting, so "e + combining
# acute" and "é" must tokenise identically. Generated from Python's own tables.
comp = {}
for cp in range(0x110000):
    ch = chr(cp)
    d = unicodedata.decomposition(ch)
    if not d or d.startswith('<'):
        continue
    parts = d.split()
    if len(parts) != 2:
        continue
    a, b = int(parts[0], 16), int(parts[1], 16)
    # exclusions: singletons and non-starter decompositions never recompose
    if unicodedata.combining(chr(a)) != 0:
        continue
    if unicodedata.normalize('NFC', chr(a) + chr(b)) != ch:
        continue
    comp[(a, b)] = cp

ccc = [(cp, unicodedata.combining(chr(cp))) for cp in range(0x110000)
       if unicodedata.combining(chr(cp))]

with open("src/unicode_nfc.h", "w") as f:
    print("#pragma once", file=f)
    print("// GENERATED by tools/gen_unicode.py -- do not edit.", file=f)
    print("// Canonical combining classes and composition pairs for NFC.", file=f)
    print("#include <stdint.h>\n", file=f)
    print(f"// {len(ccc)} combining characters", file=f)
    print("static const uint32_t kCCC[][2] = {", file=f)
    for i in range(0, len(ccc), 8):
        print("    " + " ".join(f"{{0x{c:X},{k}}}," for c, k in ccc[i:i+8]), file=f)
    print("};", file=f)
    print(f"static const int kNCCC = {len(ccc)};\n", file=f)
    items = sorted(comp.items())
    print(f"// {len(items)} composition pairs", file=f)
    print("static const uint32_t kComp[][3] = {", file=f)
    for i in range(0, len(items), 5):
        print("    " + " ".join(f"{{0x{a:X},0x{b:X},0x{c:X}}}," for (a, b), c in items[i:i+5]), file=f)
    print("};", file=f)
    print(f"static const int kNComp = {len(items)};", file=f)
print(f"NFC: {len(ccc)} combining, {len(comp)} composition pairs", file=sys.stderr)
